### ISSUE TITLE
Boilerplate code?

### ISSUE THREAD

**Issue by bofh** [rust-av/rust-av#100]
Hi,

I've decided to write a new service in Rust (instead of plain C) could you please provide me with hints how to implement the following (if that's already possible):
* open file (let's say it is mp4);
* get metadata (duration, framerate, etc.);
* sequentially decode every frame.

Thanks.

**Comment by lu-zero** [comment]
The mp4 demuxer from mozilla is yet to be integrated here, you can look at `ave` and `avp` for the other questions :)
