### ISSUE TITLE
Reduce the code boilerplate

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#14]
Use [interpolate_idents](https://github.com/SkylerLipthay/interpolate_idents) to compact some boilerplate in macros.

**Comment by bkfox** [comment]
From [interpolate_idents page](https://github.com/SkylerLipthay/interpolate_idents), the project has been deprecated:

```
Because of the introduction of stable procedural macro support in Rust 1.30.0, it is now possible to accomplish what this crate set out to accomplish using entirely stable code. Please try @dtolnay's [`paste`](https://crates.io/crates/paste) crate to see if it can fulfill all of your current use cases. `paste` can be used in stable production environments and is not nearly as prone to breakage between Rust versions.
```

**Comment by lu-zero** [comment]
Right now for each Decoder, Encoder, Demuxer and Muxer we end up implementing some traits.

With the procedural macros we could probably have a custom `derive` to reduce the implementation (e.g. how we prepare the `Descriptor`s)

We could go over the whole API and see if we can improve it in a different way as well.

Thank you a lot for volunteering :)
