### ISSUE TITLE
Current state

### ISSUE THREAD

**Issue by FireMasterK** [rust-av/rust-av#140]
Hi,

I was wondering if it is possible to mux videos in the current state of this library

The readme says this:
> eventually demuxer, muxers and codecs

However, the following file exists which suggests may no longer be true: https://github.com/rust-av/rust-av/blob/master/format/src/muxer.rs

I'm wondering if there is support for Muxing videos.

**Comment by Luni-4** [comment]
Yes, it is possible to mux videos, have a look at the https://github.com/rust-av/ave repository. 

We need to add simpler examples though and simplify some APIs, still working on that :)

**Comment by Luni-4** [comment]
I clarified the README, let me know if it's better now. Thanks for the catch!

**Comment by FireMasterK** [comment]
Awesome, thanks!
