### ISSUE TITLE
Question | Muxing audio and video of type `video/mp4`

### ISSUE THREAD

**Issue by spikecodes** [rust-av/rust-av#141]
How would I combine a video clip of type `video/mp4` and an audio of type `video/mp4` using rust-av?

**Comment by lu-zero** [comment]
Right now we do not have a mp4 muxer nor demuxer. Help welcome :)

**Comment by FireMasterK** [comment]
Is it possible to Mux such videos in Mkv? We do not need to re-encode these audio/video media

**Comment by lu-zero** [comment]
we have a muxer and demuxer for [mkv](https://github.com/rust-av/matroska) that probably would work for your purpose or would take little additions to work for you.

You may look at [ave](https://github.com/rust-av/ave) for an example of transcoding.

**Comment by spikecodes** [comment]
Thanks for your prompt response! Does rust-av support media conversions (from mp4 to mkv) currently?

**Comment by lu-zero** [comment]
So far nobody integrated https://github.com/mozilla/mp4parse-rust but would be feasible to use it for the purpose, otherwise there are [minimp4 bindings](https://github.com/darkskygit/minimp4.rs) and oxidizing it could be practical.

**Comment by spikecodes** [comment]
Thank you for your help!
