### ISSUE TITLE
Document better which are our communication channels (IRC, Zulip, etc)

### ISSUE THREAD

**Issue by ghost** [rust-av/rust-av#152]
The link on the main page still links to Freenode? Will this operation's chat be moving to Libera or not? If there has already been a change then we should change that so newcomers are not confused.

**Comment by lu-zero** [comment]
Our main venue is [zulip](https://rust-av.zulipchat.com/), once the dust settles the bridge will probably move.

**Comment by Luni-4** [comment]
Closed in 598f792
