### ISSUE TITLE
Mixup in get_height function

### ISSUE THREAD

**Issue by mahanstreamer** [rust-av/rust-av#155]
Shouldn't h_ss be v_ss in get_height() in the pixel.rs file? Since v_ss is vertical?
`pub fn get_height(self, height: usize) -> usize {
        (height + ((1 << self.h_ss) - 1)) >> self.h_ss
    }`

And vice versa for the get_width function - v_ss should be h_ss (since width is vertical)?

Just making sure.

**Comment by Luni-4** [comment]
Ouch, you're right, they should be swapped. Feel free to send a corrective PR, thank you!

**Comment by Luni-4** [comment]
Closed by #156
