### ISSUE TITLE
How does `Error::MoreDataNeeded(usize)` work?

### ISSUE THREAD

**Issue by FreezyLemon** [rust-av/rust-av#183]
https://github.com/rust-av/rust-av/blob/0134f4a153119ece6d48a3bf62f25220db3489ff/format/src/demuxer.rs#L21-L22

Does `MoreDataNeeded(100)` mean that we need 100 *more* bytes than we have at the moment? Or does it mean that we need 100 bytes in total?

I'm asking because of this:
https://github.com/rust-av/rust-av/blob/0134f4a153119ece6d48a3bf62f25220db3489ff/format/src/demuxer.rs#L147-L159

`if len >= needed` in particular. If we want to handle `MoreDataNeeded(0)`, why not just check `needed == 0`?

**Comment by lu-zero** [comment]
The idea is that you request the least amount of data you need to possibly progress parsing.

**Comment by FreezyLemon** [comment]
Hm.. let me explain with an example what I mean:

My data is 20 bytes. I run `Element::parse(data)` but the Element is actually 50 bytes long, so the 20 bytes are not enough.
Should it return `MoreDataNeeded(50)` or `MoreDataNeeded(30)`?

**Comment by lu-zero** [comment]
I see what you mean, we need to document it properly, we are not consuming if we cannot complete the parsing so it would be `MoreDataNeeded(50)`.

**Comment by FreezyLemon** [comment]
Okay, thanks for the info. I was asking because of rust-av/matroska#135.
