### ISSUE TITLE
Use macros 1.1 to hide boilerplate

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#19]
The current idea for the rust-av API is to use a builder pattern and keep the context struct hidden.

The builders may have a function to `probe()` data and confirm they are able to process it (demuxer and decoders) and then the normal builder pattern to configure the object by passing `options` and input or output objects (e.g. a demuxer needs a BufRead object, a decoder would need a demuxer object).

A good deal of the builder can be probably autogenerated as can be seen from the dumb "normal" macros I drafted [here](https://github.com/rust-av/rust-av/blob/demuxer/src/format/demuxer/demux.rs#L60).

**Comment by lu-zero** [comment]
The procedural macros might be useful, but the current amount of boilerplate is now sort of bearable.

**Comment by Luni-4** [comment]
With the introduction of GAT we can re-think the library in a different way, so this issue is no more necessary
