### ISSUE TITLE
Macro templating for function names

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#2]
In multimedia there is the tendency of having small building blocks with multiple variants, rust macro system does not provide a simple way to collate two identifiers to create a function name.

rfc almost there.

**Comment by lu-zero** [comment]
The [interpolate_idents](https://github.com/SkylerLipthay/interpolate_idents) crate provides a macro that can be leveraged meanwhile.

**Comment by Luni-4** [comment]
@lu-zero 

We could use the `paste` crate for this problem. I think we should close this one

**Comment by lu-zero** [comment]
Yes :)
