### ISSUE TITLE
Use slog internally

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#22]
[slog](https://github.com/slog-rs/slog) seem to provide a good deal of functionality.

To be debated how to pass around the logging context.

**Comment by lu-zero** [comment]
The consensus is to start using the plain log crate and then consider it again. [fern](https://github.com/daboross/fern) might already satisfy the needs of most users.

**Comment by sdroege** [comment]
slog has the problem that it's quite complex and probably does much more than what you need, making simple usage more complicated than needed. I switched away from slog in my projects for that reason for now. slog is great but it's like using alien technology when all you need is a hammer.

**Comment by lu-zero** [comment]
I cleaned up matroska and used the [pretty_env_logger](https://github.com/seanmonstar/pretty-env-logger) for the example. (I'll move the tools in a separate crate to not add a spurious dependency later)

**Comment by Luni-4** [comment]
`slog` is too complex for our needs, so let's close this up.
