### ISSUE TITLE
Consider bytes

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#27]
[bytes](https://github.com/carllerche/bytes) is an efficient container for storing and operating on continguous slices of memory.

Concerns open on how to make it work with aligned memory.

**Comment by lu-zero** [comment]
Bytes is not working for our use case. It should be dropped as soon as possible.

**Comment by sdroege** [comment]
> Bytes is not working for our use case.

Yeah it's very limited, I also couldn't use it in many similar use-cases :)

**Comment by lu-zero** [comment]
Probably we could spend a couple of days and adapt the rav1e plane/tiling system sooner or later. :)
