### ISSUE TITLE
Consider using tokio.

### ISSUE THREAD

**Issue by quadrupleslap** [rust-av/rust-av#31]
There is a **lot** of stuff in `tokio_io`, `tokio_core` and `futures` that looks relevant to this project - I'm not sure it'll be useful, but there seems to be a lot of groundwork on pipelining, multiplexing, encoding, decoding, etc. that you could reuse. ^_^

**Comment by lu-zero** [comment]
I do not have enough experience with those libraries to say how useful the could be, so far seems that the consensus is to keep the `rust-av` core crate with the least amount of non-optional dependencies (and make mainly a set of traits and data structs).

Surely would be interesting to provide a futures-based infrastructure in the future, but I'd rather not force that patter as the only usage.

@Geal, you used tokio and futures already, what's your opinion?

**Comment by sdroege** [comment]
What would you use futures or tokio for in rust-av? rust-av is a completely sync and single-threaded API at this point, and it seems like it would make more sense for layers on top of rust-av to make use of this instead.

**Comment by quadrupleslap** [comment]
Yeah, I agree, feel free to close!

**Comment by sdroege** [comment]
Thanks for bringing this up nonetheless :) Some higher-level API around futures/tokio could certainly make sense on top of what is there in rust-av currently.

**Comment by Luni-4** [comment]
This one seems solved
