### ISSUE TITLE
Support for extended constant tables

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#33]
In multimedia is quite common to have large tables of constant values, currently rust has a number of quirks that makes building and using constant arrays a little more unwieldy than it should: 

- [x] [fill arrays](https://github.com/rust-lang/rfcs/issues/2092) using generators (procedural macros might make the situation a little nicer).
- [x] generating pairs of elements using macros (writing a macro for this is more convoluted than it should).
- [x] [indexing a constant](https://github.com/rust-lang/rust/issues/29947) is not stable yet but seems that this will end up in stable sooner.

**Comment by Luni-4** [comment]
@lu-zero 

The third point is stable now. Is the second one stable too?

**Comment by lu-zero** [comment]
the second one is something I didn't explored fully yet.

**Comment by Luni-4** [comment]
Ok, got it. Thanks! :)

**Comment by Luni-4** [comment]
Every bullet point should be addressed upstream, please @lu-zero verify if I'm not mistaken :)
