### ISSUE TITLE
LGPL 2.1 only incompatible to Apache version 2

### ISSUE THREAD

**Issue by est31** [rust-av/rust-av#37]
As you may know, the GNU Lesser General Public License version 2.1 only, under which this project seems to be licensed, is incompatible to the Apache license, version 2, according to the FSF and other parties. This means that you may not be able to use rust-av together with Apache licensed source code. This causes two issues for Rust projects:

* Rust can't really do dynamic linking so if you are using rust-av in your project you most likely will have to keep other components of your project under LGPLv2.1 compatible licenses.
* Several important projects in the Rust ecosystem are still licensed under the ASLv2.0 only

In combination these two facts hamper the adoptability of this codebase. Therefore I propose that the license is changed to one compatible with the ASL2.0. Good choices include:

* LGPLv2.1 *or later*, the closest choice to the project's current licensing
* MPLv2.0, a popular copyleft license in the Rust ecosystem
* Apache2.0/MIT dual licensing, the most popular license choice in the Rust ecosystem

I'm no fan of the ASLv2.0 myself, I also file issues for the repositories that are only using the ASLv2.0 for the very same reason.

Edit: I should also point out that I am no lawyer etc etc.

**Comment by lu-zero** [comment]
Thank you for pointing it out, as [stated](https://github.com/rust-av/rust-av/blob/master/CONTRIBUTING.md#license) switching to MIT is an option on the table. 

Adding the "or later" seems the easiest path though.

**Comment by est31** [comment]
"LGPLv2.1 or later" will make it easier for free software/open source projects to use this library that have a compatible license, but all projects that have incompatible licenses, including proprietary ones, will most likely still want to make use of dynamic linking, which in Rust is not very easy. So I think it would be best for everyone if there was a switch to Apache2.0/MIT.

As for whether those licenses will bring you contributors, I think they will. There is no better way to know than to try it out :). Those contributors who want the LGPL or the GPL or other licenses can still contribute via writing disableable components under that license (the best way to represent those components is probably to put them into a separate crate that the user can use if they want to use that particular implementation). Also, as the project has only few contributors, one can easily start out with the MIT and you can always switch to the LGPL later, but the other way round keeps getting harder with a growing number of contributors (because you've got to ask them all :p).

**Comment by lu-zero** [comment]
@ftomassetti and @Geal I'd guess we can switch the base license to MIT as the rest of the crates. I already contacted Kostya about it.

**Comment by lu-zero** [comment]
Kostya is fine with a license change and would like not to spend any time on that issue.

**Comment by Geal** [comment]
Fine by me

**Comment by ftomassetti** [comment]
It sounds a good idea to me

**Comment by lu-zero** [comment]
Ok, I'll switch the main license to MIT now then.
