### ISSUE TITLE
Use the byteorder crate instead of NIH'ing it

### ISSUE THREAD

**Issue by nox** [rust-av/rust-av#38]
https://github.com/rust-av/rust-av/blob/31f728df88b41adb82de2bae530f74ddb195cd18/bitstream/src/byteread.rs#L14

https://github.com/rust-av/rust-av/blob/77d3cd19c0506d50957009ae0cb8fee35b3a81b7/bitstream/src/bytewrite.rs#L89

These two modules can be replaced by the byteorder crate.

**Comment by lu-zero** [comment]
The byteorder crate ergonomics are a bit terrible IMHO, I guess nothing prevents some willing person to replace the internals with byteorder to just keep the short names and fix #39.

**Comment by nox** [comment]
Yeah, byteorder is usually just used in helper functions for the most primitive reading functions.

That being said, these modules define both little and big endian convenience functions, at which point byteorder may not be necessarily less pleasant to use:

```rust
use byteorder::{BE, ByteOrder, LE};

foo.read_u8::<BE>();
foo.read_u16::<LE>();
```

**Comment by lu-zero** [comment]
The gst-rs project seem to [wrap](https://github.com/sdroege/gst-plugin-rs/blob/master/gst-plugin/src/bytes.rs) byteorder to shorten the methods, I guess I can follow that pattern.
