### ISSUE TITLE
Track changes of the subcrates, as av itself is mostly empty

### ISSUE THREAD

**Issue by Coding-Doctors** [rust-av/rust-av#43]
From the discussion in #42

**Comment by Coding-Doctors** [comment]
So what I'm thinking is to run Travis for each of the subcrates, eg change dirs, but run those as separate jobs. It'd look similar testing against different rust versions, although it'd be crates.

**Comment by lu-zero** [comment]
Sounds pretty and straightforward :) I'm sold.

**Comment by Coding-Doctors** [comment]
Alright then, I changed around to a "final" version of what I'm thinking, so if the above works for you then I'll send in another pr, might have to fidel around to get coveralls to get everything, but we'll see.
