### ISSUE TITLE
The standard collections panic on oom

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#5]
Considering situations such as managing `8k` or `UHD` video it is not really optimal to panic on out of memory situation (even more if they are recoverable).

https://github.com/rust-lang/rust/issues/29802

**Comment by bluss** [comment]
Note that the standard collections call abort on oom, not panic. They do however have panics for arithmetic overflow errors sometimes.

**Comment by lu-zero** [comment]
Thank you for the clarification =)

**Comment by Luni-4** [comment]
@ lu-zero

Even this `rfc` is landed. We should close this one too.

**Comment by lu-zero** [comment]
Ok
