### ISSUE TITLE
Add support for a user-supplied "identifier" to Timeinfo

### ISSUE THREAD

**Issue by sdroege** [rust-av/rust-av#50]
In many cases it's useful to know to which `Packet` and `Frame` corresponds or the other way around. This can currently be done only by matching timestamps, which is not great.

In ffmpeg it's possible to attach some "opaque" data for this reason. For my use cases it would already be enough to be able to attach a `u64` or similar that allows for such identification, and is guaranteed to be copied from input to output by codec implementations.

**Comment by lu-zero** [comment]
This is something I'd manage later. 

Ideally `Packet` and `Frame` would be able to carry arbitrary amount of data as an optional that you can `downcast()` to get the data back.

**Comment by sdroege** [comment]
`Option<Arc<Any>>`? Sounds good to me :)

**Comment by lu-zero** [comment]
Having `user_private` in Timeinfo makes it non-Copy and if needed we'd have to implement PartialEq for it manually.

I guess we could introduce it, play a bit and keep a note to consider overhauling this later if needed.
