### ISSUE TITLE
Various rust-av crates depend on out-of-repository crates via `path`

### ISSUE THREAD

**Issue by sdroege** [rust-av/rust-av#55]
See summary. It's not a problem for `rust-av` itself but all the other crates, which require `rust-av` and others to be checked out one level above themselves.

It would be good to update these to directly use `git = "...."` instead of `path = "...."` so that other crates can directly depend on them and cargo can fetch the code as needed without user intervention.

Note: for `rust-av` itself using `path` is fine, or generally if it's only pointing at other crates inside the same repository.

**Comment by lu-zero** [comment]
I agree that the current solution is suboptimal, I hoped that [alternative registries](https://github.com/rust-lang/rust/issues/44931) could be leveraged to keep the ease of local development that I currently have with paths, but looks like there are still some details to iron out.

Anybody willing to go over the repos and replace the paths with the git references is welcome to do it :)

**Comment by sdroege** [comment]
Those seem to be all, the other repositories don't seem to have such dependencies. This is going to make my life easier and at least let my travis jobs succeed :)

**Comment by lu-zero** [comment]
Thank you!
