### ISSUE TITLE
Ownership of the `av` crate on crates.io

### ISSUE THREAD

**Issue by panicbit** [rust-av/rust-av#58]
Hi, I'm the current holder of `av` on crates.io, but until now I haven't published anything proper under that name yet and I'm not planning to publish my own rust-av anymore.

If you are interested in using `av` for your project just let me know who I should transfer ownership to.

**Comment by lu-zero** [comment]
That would be awesome! Thank you a lot :)

**Comment by panicbit** [comment]
Sent you an invite

**Comment by lu-zero** [comment]
I'm not seeing it even after 2 hours, something apparently went wrong...

**Comment by lu-zero** [comment]
The email notification did not appear but I managed to get in from crates.io directly.

Thank you a lot again :)

**Comment by Luni-4** [comment]
Seems solved, close this one.
