### ISSUE TITLE
Packet Abstraction

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#6]
A **packet** is a defined amount of compressed data, its time reference (pts, dts) and optional ancillary data.

At least the data and the ancillary data should be reference counted to allow multiple usage without copy, e.g. multiple muxing.

**Comment by lu-zero** [comment]
Question:
- Should the `Packet` have a a `Stream` attached?

**Comment by Luni-4** [comment]
It seems to be complete, close this one
