### ISSUE TITLE
Get ready to publish all crates on crates.io

### ISSUE THREAD

**Issue by gibix** [rust-av/rust-av#65]
is necessary in order to be used as dependency by other projects on crates.io

Subcrates
- [x] bitstream
- [ ] data
  - [x] Make sure the crate builds on stable
  - [x] Make sure the tests run
  - [ ] Write the documentation
- [x] format
  - [x] Make sure the crate builds on stable
  - [x] Make sure the tests run
  - [ ] Write the documentation
- [ ] codec
  - [x] Make sure the crate builds on stable
  - [x] Make sure the tests run
  - [ ] Write the documentation

**Comment by Luni-4** [comment]
What's the status of this one?

**Comment by Luni-4** [comment]
Closed in favor of #119
