### ISSUE TITLE
Frame Abstraction

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#7]
It holds **raw** data, the timing information (pts, dts), a reference to the format used (e.g. pixel and sample description), optional ancillary data and additional information.

The data pointers must be reference counted.

- [x] Implement a basic frame for the video
   - [x] Validate its usage for encoders
   - [x] Validate its usage for decoders
- [x] Implement a basic frame for the audio
   - [x] Validate its usage for encoders
   - [x] Validate its usage for decoders

**Comment by lu-zero** [comment]
[here](https://play.rust-lang.org/?gist=6dac846661e7794a083dcdd6934ae16c&version=stable&backtrace=0)
``` rust
struct ByteBuffer {}

enum Format {
    Audio(AudioFormat),
    Video(VideoFormat),
    Subtitle(SubtitleFormat),
    Opaque(OpaqueFormat),
}

enum SideData {
    Name(Box<NameData>)
    ...
}

struct Frame {
    data: ByteBuffer,
    format: Format,
    pts: Option<i64>,
    dts: Option<i64>,
    duration: Option<i64>,
    meta: Vec<(String, Value)>
    side: Vec<Box<SideData>
}

impl Frame {
    fn new(format: Format) -> Frame {
        let data = match format {
            Audio(a) -> a.alloc(), 
            Video(v) -> v.alloc(), 
            ...
        };
        Frame {data: data, format: format, pts: None, dts: None }
    }
    
}
```

A draft of the fields

**Comment by lu-zero** [comment]
Video frame implemented and validated using [vpx-rs](https://github.com/rust-av/vpx-rs) middle level api.

**Comment by Luni-4** [comment]
It seems to be complete, close this one
