### ISSUE TITLE
Container Format Abstraction

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#8]
It is used for muxing and demuxing.

Produces and consumes [packets](https://github.com/rust-av/rust-av/issues/6) and assigns them to [streams](https://github.com/rust-av/rust-av/issues/10).

**Comment by lu-zero** [comment]
Produces and consumes [packets](https://github.com/rust-av/rust-av/issues/6) and assigns them to [streams](https://github.com/rust-av/rust-av/issues/10).

**Comment by lu-zero** [comment]
[Kostya](http://codecs.multimedia.cx/?p=1022) design tends to differentiate three kind of container formats:
- those that provide packets containing a single frame give each a timestamp
- those that provide packets containing a single frame but provide the timestamp only to certain packets (plausibly the keyframes).
- those that provide packets containing partial data and do not provide timestamps related to the packet.

The initial API would work only for the former type.

**Comment by Geal** [comment]
how do they synchronize with audio for the partial data case?

**Comment by lu-zero** [comment]
The timestamp information is up to the reader to decide (e.g. raw PCM) or you have to assemble the data up to some point (e.g. mpeg ps and ts) and maybe compute the timestamp from the container reference (coarse) and the codec information (precise but not always matching).

That would require parsers and I'd rather touch that part later =)

**Comment by lu-zero** [comment]
High level API-wise would be nice if the actual demuxer object is assembled using a builder pattern:

``` rust
let builders_list = list_of_possible_demuxers_of_interest();
let probe_data = input.fill_buffer();

// The probe function takes a reference to a [u8] and gets the most plausible demuxer
let demuxer_builder = probe(builders_list, &probe_data).unwrap();

// you can build multiple demuxers, open() will try to read the least amount of data
let demux = demuxer_builder.set_input(input).set_options(options).open().unwrap();
```

The API should make at least an effort to let the user query the format without consuming too much data.

``` rust
// get_streams() will try to figure out the Streams available from the container header if present
let streams = demux.get_streams().unwrap();
```

The demuxer object can act as an event loop

```
for Some(ev) in demuxer {
     match ev {
         DemuxEvent::Packet(packet) => ...,
         DemuxEvent::NewStream(stream) => ...,
         DemuxEvent::NewChapter(chapter) => ...,
     }
}
```

Or just provide an iterator with just Packets

``` rust
for Some(packet) in demuxer.iter_packets() {
    ...
}
```

**Comment by lu-zero** [comment]
Implemented.
