### ISSUE TITLE
Compressed Format Abstraction

### ISSUE THREAD

**Issue by lu-zero** [rust-av/rust-av#9]
Encoding and decoding information.

- [x] Provide the minimal API for lookup
- [x] Provide a basic decoupled API for decoding
- [x] Provide a basic decoupled API for encoding
- [x] Support a generic way to query and set optional parameters

**Comment by lu-zero** [comment]
The decoding consumes [packets][1] and produces [frames][2], the encoding consumes [frames][2] and produces [packets][1]

[1]: https://github.com/rust-av/rust-av/issues/6
[2]: https://github.com/rust-av/rust-av/issues/7

**Comment by Luni-4** [comment]
It seems to be complete, close this one
