### ISSUE TITLE
Add a newsletter/road-map

### ISSUE THREAD

**Issue by xd009642** [rust-av/rust-av#98]
So I'm quite interested in AV applications and generally replacing libav code with rust but there's a lot of projects in the rust-av organisation and it can be hard to see where to go to find how mature different parts are. The embedded working group seemed to solve this through the embedded newsletter and also a presence on the official and unofficial rust discords.

Alternatively, I can just say what I'm interested in and hopefully get pointed to the right place. I'd like to decode AVI/webm videos and WAV and FLAC audio. It would also be great to have something similar to filter graphs in libav (although I'm not opposed to implementing that myself)

**Comment by lu-zero** [comment]
Currently I'm tempted to ask for a stream in zulip to augment our irc channel.

I do agree we should provide more information on what's the current status.

**Comment by xd009642** [comment]
So if anyone uses discord I've asked the unofficial discord if they'd consider adding a multimedia channel for anything audio or visual in rust. I personally use the discord to talk to people involved in ndarray for scientific computing things and various people involved in embedded systems.

Here's the invite link if you want to check it out (I'll update if they actually add the channel) 
https://discord.gg/ndHX6u

**Comment by Luni-4** [comment]
We could also use [gitter](https://gitter.im/) as chat platform, you can access to it using your GitHub profile. I think it's much more developer-oriented, but even `discord` is a good choice for me.

**Comment by xd009642** [comment]
Gitter works for me I just found the notifications kinda annoying but I didn't spend much time trying to configure them

**Comment by xd009642** [comment]
@lu-zero any update on this? I think a gitter would be quite nice :smile:

**Comment by lu-zero** [comment]
Zulip does not seem easy enough to use so https://gitter.im/rust-av/ is now up.

**Comment by Luni-4** [comment]
Since we now have `gitter`, I think we can close this one.
